name: base

services:
  database:
    container_name: base-database
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    env_file: .env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - base-net

volumes:
  pgdata:

networks:
  base-net:
